#!/bin/sh
# Build the documentation: regenerate the language map from the
# parallel sidebars, render the language projects into ../site/, then
# apply the offline repairs so the result works from a plain file tree.
# Verify with:  python3 offline/smoketest.py site/en site/de
set -e
cd "$(dirname "$0")"

# The language projects; every loop below and the gen_langmap call use
# this one list — a third language is one more entry here plus its
# project directory.
LANGS="en de"

# Quarto is pinned; upgrades are deliberate (build with
# ALLOW_UNPINNED_QUARTO=1, run the smoketest, eyeball a page, move the
# pin). Keep equal to the qdaPy/qdaR pins so the sites stay in step.
PINNED="1.10.18"
ACTUAL="$(quarto --version)"
if [ "$ACTUAL" != "$PINNED" ] && [ -z "$ALLOW_UNPINNED_QUARTO" ]; then
  echo "doc/build.sh: quarto is $ACTUAL, pinned is $PINNED" >&2
  exit 1
fi

# These docs keep their pages plain, generator-neutral markdown: any
# figure would be generated by a build step, never by an executable
# chunk in a page (sites that want executable cells simply drop this
# guard — the theme supports them).
if grep -rn --include='*.qmd' '^```{' $LANGS; then
  echo "doc/build.sh: executable code chunks found (see above)" >&2
  exit 1
fi

# gen_langmap needs PyYAML; any python3 with pyyaml serves. The qdaPy
# docs venv has it and is the default where present.
GEN_PY="${GEN_PY:-$HOME/.venvs/qdapy-docs/bin/python}"
command -v "$GEN_PY" >/dev/null 2>&1 || GEN_PY=python3

# This repository IS the theme: the single copy of _extensions/ and
# font/ lives at the repository root, and each language project gets a
# disposable mirror before the render, because Quarto only resolves
# extensions and resources inside a project directory.
for lang in $LANGS; do
  rsync -a --delete ../_extensions/ "$lang/_extensions/"
  rsync -a --delete ../font/ "$lang/font/"
done

# Quarto does not clear removed pages from the output dir; without a
# fresh start deleted pages would linger in the published site.
for lang in $LANGS; do rm -rf "../site/$lang"; done

"$GEN_PY" ../script/gen_langmap.py --extra-js shared/versions.js $LANGS
for lang in $LANGS; do quarto render "$lang"; done
python3 ../offline/postprocess.py ../site/en ../site/de

# The same pages once more as one linked PDF per language (Typst, Noto
# Sans embedded), downloadable via the navbar's PDF icon.
"$GEN_PY" ../print/make_pdf.py en ../site/en/easyqda-theme-documentation.pdf fre.ms
"$GEN_PY" ../print/make_pdf.py de ../site/de/easyqda-theme-Dokumentation.pdf fre.ms
echo "Done: open ../site/en/index.html"
