#!/usr/bin/env python3
"""Example script for the figure convention (see the README beside it).

Writes a minimal vector graphic to asset/generiert/ — with no
dependencies, so the chain is reproducible on any machine. Real
scripts use matplotlib, ggplot2 or the like and write their result
just the same as a file under asset/generiert/ (gitignored — what
comes from code is not committed but generated by build.sh or CI).
Delete as soon as real figures exist.
"""

from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "asset" / "generiert" / "beispiel.svg"
OUT.parent.mkdir(parents=True, exist_ok=True)

ITEMS = ["one", "two", "three"]

bars = "".join(
    f'<rect x="{20 + i * 90}" y="20" width="70" height="30" rx="4" '
    f'fill="#4a7" /><text x="{55 + i * 90}" y="40" font-size="13" '
    f'text-anchor="middle" fill="#fff">{name}</text>'
    for i, name in enumerate(ITEMS))

OUT.write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" width="290" height="70" '
    f'viewBox="0 0 290 70" role="img" aria-label="Example">{bars}</svg>\n',
    encoding="utf-8")
print(f"wrote {OUT.relative_to(REPO)}")
